### ISSUE TITLE
Add a view to show past workshops?

### ISSUE THREAD

**Issue by ChillarAnand** [pythonindia/wye#321] opened 2016-08-09 20:48 UTC
I think we can enhance profile page of tutor to display all workshop he conducted like github show commits in profile page. So each user profile page will be one place to get all information about the tutor and history .

**Comment by pulkitpahwa** [comment] 2016-09-24 11:31
Do you think this would be a good feature?

How about a view for the list of all workshops that were organized in the past?

**Comment by vnbang2003** [comment] 2016-09-24 12:33
once we reach 200 + workshop page will go out of control. Instead we can display in profile users workshop they conducted.

**Comment by vnbang2003** [comment] 2016-10-16 11:55
Closing this ticket as by design we want to show details on profile page.
This details will be soon display in profile page .

**Closed by vnbang2003** 2016-10-16 11:55 UTC
Labels: hacktoberfest
