### ISSUE TITLE
Workshop details page shows is active true in table

### ISSUE THREAD

**Issue by shankisg** [pythonindia/wye#243] opened 2016-01-08 16:24 UTC
Workshop details page show **is active true** in table, Is it expected?
https://pythonexpress.in/workshop/13/

**Comment by vnbang2003** [comment] 2016-03-01 05:47
@shankisg We need to display on workshop with are active, Deactivated workshop is equal to delete .
Marking it as not a bug.

**Closed by vnbang2003** 2016-03-01 05:47 UTC
Labels: invalid
